[workspace]
members = [
    ".",
    "openvr",
]

[package]
name = "clekey-ovr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openvr = { path = "openvr" }
sdl2 = "0.35"
glium = "0.32"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.17"
