[workspace]
members = [
    ".",
    "openvr",
]

[package]
name = "clekey-ovr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.17"
once_cell = "1.15.0"
skia-safe = { version = "0.55.0", features = ["gl", "textlayout"] }
gl = "0.14.0"
cfg-if = "1.0.0"
openvr = { path = "openvr", optional = true }
glam = { version = "0.21.3", features = ["serde"] }

[target."cfg(windows)".dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_UI_Input_KeyboardAndMouse",
]

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[target."cfg(windows)".features]
default = ["openvr"]

[features]
# by build.rs, 
#  - debug_window is enabled in default on debug build (cfg(debug_assertions))
default = []
debug_window = []
