[workspace]
members = [
    ".",
    "openvr",
]

[package]
name = "clekey-ovr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openvr = { path = "openvr" }
sdl2 = "0.35"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.17"
once_cell = "1.15.0"
skia-safe = { version = "0.55.0", features = ["gl"] }
gl = "0.14.0"
